set nocompatible	" Vi incompatible settings (must be first as it affects other options)


set backup		" keep a backup file
set backspace=indent,eol,start " allow backspacing over everything in insert mode
set hidden		" allow multiple files by hiding instead of closing
set history=50		" keep 50 lines of command line history
set viminfo+=<1000	" copy up to 1000 lines (default 50)
set autoindent		" auto indent on newline if starting from indent
set wrap		" enable line wrap
set linebreak		" wrap lines at end of word rather than mid
set ttimeoutlen=0	" allows exiting insert mode instantly and removes lag on O, may cause issues with key combinations
set spelllang=en_ca,cjk " Canadian spellcheck, ignore east asian
set mouse=a		" enable mouse in all modes

set hlsearch		" search result highlighting
set incsearch		" show matches while typing search pattern
set ignorecase		" case insensitive searching
set smartcase		" disable ignorecase when inputting uppercase

set ruler		" always show cursor position
set showcmd		" display incomplete commands in bottom right
set scrolloff=5		" minimum visible lines above and below cursor
set number		" number lines
set cursorline		" highlight current line
set nolist		" do not display EOL or TAB markers
set shortmess+=I	" disable intro message when opening vim

syntax on		" syntax highlighting
highlight LineNr ctermfg=250		" inactive line number colour
highlight CursorLineNr ctermfg=245	" active line number colour
highlight CursorLine cterm=NONE ctermbg=254	" current line highlight colour

" different line/number colour when in insert mode
au InsertEnter * hi CursorLine cterm=none ctermbg=153 | hi CursorLineNr ctermfg=75
au InsertLeave * hi CursorLine cterm=none ctermbg=254 | hi CursorLineNr ctermfg=245


" change .vim, swap, backup, viminfo directories
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
set directory=~/.local/share/vim/swap//,/tmp
set backupdir=~/.local/share/vim/backup,/tmp
set viminfo+=n~/.local/share/vim/viminfo	" old sessions will use and recreate old location

" set backup files to contain timestamp in format _YYYYMMDD-HHMM
let backupextvar = strftime("%Y%m%d-%H%M")
let backupextvar = "set backupext=_". backupextvar
execute backupextvar



" ctrl-U in insert mode cannot be undone unless we break the undo with ctrl-g u
inoremap <C-U> <C-G>u<C-U>


" always jump to the last known cursor position unless invalid or first line
autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif


" command to see unsaved changes to current file
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif



" autoload the session when running vim
au VimEnter * nested :call sessionpersist#LoadSession()

" autosave the session on exiting vim
au VimLeave * nested :call sessionpersist#UpdateSession()
