#!/usr/bin/env bash
popup_duration="3"

for i in $(seq 1 ${popup_duration}); do \
	date +"%Y年%-m月%-d日（%a） %H:%M:%S %Z"; \
	TZ="CET" date +"%Y年%-m月%-d日（%a） %H:%M:%S %Z"; \
	TZ="Japan" date +"%Y年%-m月%-d日（%a） %H:%M:%S %Z"; \
	sleep 1; \
done \
| dzen2 -w 400 -h 50 -x 20 -y 20 -fg '#282828' -bg '#ff99cc' -fn '-*-ipapgothic-medium-r-normal--13-*-*-*-*-*-iso10646-1' -l 2 -u -sa c
